### ISSUE TITLE
sentinl 5.2.2 & Kibana 5.2.2 : initialization fails

### ISSUE THREAD

**Issue by fbaligand** [sirensolutions/sentinl#125]
Hi,

I installed sentinl 5.2.2 on Kibana 5.2.2 successfully.
Then, when I start Kibana, I see the following log every 30s :
`log   [14:28:55.609] [info][status][Sentinl] No indices found, Initializing`

And when I go to "Kibana Console", I see that no one sentinl index is created.
=> It seems that sentinl initialization fails on Kibana 5.2.2.

**Comment by lmangani** [comment]
Thanks for the report. I believe this is related to changes in the client usage, but might already be fixed in our upstream private, assigned to @SergeyBondarenko to confirm

**Comment by fbaligand** [comment]
At Kibana startup, I see well the following logs :
` log   [14:56:55.575] [info][status][Sentinl] Core Index check...`
` log   [14:56:55.578] [info][status][Sentinl] Alarm Index check...`

But never `Creating Sentinl core Index...` (log defined in helpers.js:59)
As if 'indices.exists' function was never called...

**Comment by fbaligand** [comment]
@lmangani @SergeyBondarenko 
I just sent a PR that fix the problem.
It also fix sentinl alarm index check.

**Comment by lmangani** [comment]
@fbaligand thanks!
@SergeyBondarenko can you validate and merge to our private?

**Comment by SergeyBondarenko** [comment]
@lmangani this bug is resolved already. The fix is in the master branch, in https://github.com/sirensolutions/sentinl-private repo. Today, I'm going to sync the branches and produce 5.3.2 release.

**Comment by SergeyBondarenko** [comment]
Try the master branch.

**Comment by fbaligand** [comment]
Hi,

If you speak about master branch from public repository, I already tested with the very last version (no commit since then) and I reproduced the issue. Then I fixed the issue and pushed the PR. 

If you speak about private repository, I have no access to it.

**Comment by fbaligand** [comment]
Sorry @SergeyBondarenko 
I realized you made commits after my last git pull. 

I just tested with the last version and it works great !
Thanks a lot for the fix !

**Comment by fbaligand** [comment]
@SergeyBondarenko 
Do you plan also to make a new 5.2.2 release ?

**Comment by SergeyBondarenko** [comment]
@fbaligand yes, I do. But there are problems installing via kibana-plugin script. Both in Kibi 5.3.2 and Kibana 5.2.3.

```
^[[C[trex@Latitude-E5510 kibi-internal5_3_2]$ ./bin/kibi-plugin install https://github.com/sirensolutions/sentinl-private/releasesnload/tag-5.2.2/sentinl-5.3.2.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.3.2.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.3.2.zip/https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.3.2.zip-5.3.2.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```
```
[trex@Latitude-E5510 kibana]$ ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.2.3.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.2.3.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.2.3.zip/https://github.com/sirensolutions/sentinl-private/releases/download/tag-5.2.2/sentinl-5.2.3.zip-5.2.3.zip
Plugin installation was unsuccessful due to error "No valid url specified."
[trex@Latitude-E5510 kibana]$ git branch 
  5.1
* 5.2
  master
```

**Comment by fbaligand** [comment]
Your url contains "sentinl-private" repository and not "sentinl" repository.
Then, it's weird, because in your url, your tag is "tag-5.2.2" and your archive name is "sentinl-5.2.3"

**Comment by fbaligand** [comment]
I don't see this archive here : 
https://github.com/sirensolutions/sentinl/releases/tag/tag-5.2.2

Do you mean the tag on private repository ?

**Comment by SergeyBondarenko** [comment]
@fbaligand it was done in private, for tests

**Comment by fbaligand** [comment]
Ok. I have no access to private repository. 
Have you tried to install the plugin using a file URL ?
I mean : file:///path/to/sentinl.zip

**Comment by SergeyBondarenko** [comment]
@fbaligand please try the latest release https://github.com/sirensolutions/sentinl/releases/tag/tag-5.3.2, the command is 
```
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.3.2/sentinl.zip
```

**Comment by jeffforbes** [comment]
What needs to be done to get sentinl to work with ELK V5.4?

 ./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.3.2/sentinl.zip
Attempting to transfer from https://github.com/sirensolutions/sentinl/releases/download/tag-5.3.2/sentinl.zip
Transferring 5711270 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [sentinl]. Expected [5.4.0]; found [5.3.2]"

**Comment by lmangani** [comment]
Hi @jeffforbes 
Not tried 5.4.0 yet, but if you feel brave you can try clone the 5.3.2 repo, change the [version](https://github.com/sirensolutions/sentinl/blob/branch-5.3.2/package.json#L10) parameters to ```5.4.0``` and build a custom SENTINL archive to test with. In reality, this probably needs further adjustments but any input is welcome. If you give that a shot please let us know the outcome here.

**Comment by fbaligand** [comment]
@SergeyBondarenko 
I will test v5.3.2.

But it would be great to release again v5.2.2. The current issue is really a blocking bug.
if v5.2.2 does not contain the fix, it is not usable.
Today, I made a full sentinl test with kibana 5.2.2 and the following commit :
https://github.com/sirensolutions/sentinl/commit/4160a426c1f2222b4a037f0c5aeac73c585d9e2a

=> It would be great to create a new release 5.2.2-1 using this commit or to move 5.2.2 release to this commit.

**Comment by fbaligand** [comment]
I tried v5.3.2.
Concerning this issue, it works great !
Sentinl index creation works now like a charm.

However, I found another annoying issue (using v5.2.2 and v5.3.2).
=> I open a new issue for that : #128

**Comment by SergeyBondarenko** [comment]
It was fixed check new releases https://github.com/sirensolutions/sentinl/releases

**Comment by fbaligand** [comment]
I tried the fix in v5.2.2-1 and it works great !

**Comment by djtecha** [comment]
looks like this is still happening in sentinl@5.4.0-SNAPSHOT

**Comment by lmangani** [comment]
@djtecha could you attach the relevant log/error messages?

**Comment by djtecha** [comment]
Is there any other log I should look for? that's the only thing that pops up for me. it's the kibana.log

**Comment by djtecha** [comment]
out of curiosity, is there a way to pass the username and password in the sentinl plugin? Looks like it's not passing a user for me.

[2017-05-31T16:04:51,708][INFO ][c.f.s.c.PrivilegesEvaluator] No permissions for {}

**Comment by fbaligand** [comment]
@djetcha
It seems you have a very different issue from this one : an security/authentication problem between sentinl and searchguard.
=> I invite you to open a new issue for that.

**Comment by shubhamverma27** [comment]
Same issue here, Its frustrating Please help !! i am using readonly rest similar to searchguard for authentication

**Comment by fbaligand** [comment]
This issue was open for an initialization error with no security. And it is closed.
Because you have a security plugin, it is another issue.
So, I invite you either to open another issue or to give more details about your issue (logs, error message, ...) in this issue : https://github.com/sirensolutions/sentinl/issues/137

**Comment by shubhamverma27** [comment]
@fbaligand Already done check : https://github.com/sirensolutions/sentinl/issues/145
