### ISSUE TITLE
Transform 'script' evaluated to false

### ISSUE THREAD

**Issue by aquaman2** [sirensolutions/sentinl#244]
sentinl@5.5.2-SNAPSHOT

I'm working on new watcher like following (see the raw code below):
```
{
  "_index": "watcher",
  "_type": "sentinl-watcher",
  "_id": "owxh5u8zup-rl1r0vmuo5i-jkr3lz991ja",
  "_version": 22,
  "found": true,
  "_source": {
    "title": "wrLatency",
    "disable": false,
    "report": false,
    "trigger": {
      "schedule": {
        "later": "every 5 mins"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": "metrics-proxmox-*",
          "body": {
            "size": 0,
            "query": {
              "bool": {
                "filter": [
                  {
                    "range": {
                      "@timestamp": {
                        "gte": "now-5m"
                      }
                    }
                  },
                  {
                    "query_string": {
                      "query": "measurement:blockstat AND tag.host:esmaas01.xxx"
                    }
                  }
                ]
              }
            },
            "aggs": {
              "byHost": {
                "terms": {
                  "field": "tag.host",
                  "size": 100000
                },
                "aggs": {
                  "byDisk": {
                    "terms": {
                      "field": "tag.instance",
                      "size": 10,
                      "order": {
                        "_term": "desc"
                      },
                      "min_doc_count": 1
                    },
                    "aggs": {
                      "byDate": {
                        "date_histogram": {
                          "interval": "5m",
                          "field": "@timestamp",
                          "min_doc_count": 0,
                          "extended_bounds": {
                            "min": "now-5m",
                            "max": "now"
                          }
                        },
                        "aggs": {
                          "avgWrTotalTime": {
                            "avg": {
                              "field": "wr_total_time_ns"
                            }
                          },
                          "drvWrTotalTime": {
                            "derivative": {
                              "buckets_path": "avgWrTotalTime",
                              "unit": "second"
                            }
                          },
                          "avgWrOperations": {
                            "avg": {
                              "field": "wr_operations"
                            }
                          },
                          "drvWrOperations": {
                            "derivative": {
                              "buckets_path": "avgWrOperations",
                              "unit": "second"
                            }
                          },
                          "wrLatency": {
                            "bucket_script": {
                              "buckets_path": {
                                "drv1": "drvWrTotalTime",
                                "drv5": "drvWrOperations"
                              },
                              "script": "params.drv5!=0?params.drv1/params.drv5:params.drv1"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "condition": {
      "script": {
        "script": "var match=false;payload.aggregations.byHost.buckets.forEach(function(h){h.byDisk.buckets.forEach(function(d){if(d.byDate.buckets[1].wrLatency.value==0){match=true}});});match"
      }
    },
    "actions": {
      "wrLatency_alarm": {
        "throttle_period": "0h4m0s",
        "console": {
          "message": "Message:{{#payload.action_list}}Write latency:[{{value}}] on host:[{{host}}] for disk:[{{disk}}] exceeds maximum!{{/payload.action_list}}",
          "save_payload": true
        }
      }
    },
    "transform": {
      "script": {
        "script": "payload.action_list=[];payload.aggregations.byHost.buckets.forEach(function(h){h.byDisk.buckets.forEach(function(d){if(d.byDate.buckets[1].wrLatency.value==0){payload.action_list.push({host:h.key, disk: d.key, value:d.byDate.buckets[1].wrLatency.value});}});})"
      }
    }
  }
}
``` 

In the [sandbox](http://jsfiddle.net/e50L6acg/5/embedded/result/) all works fine. But when I fill all the properties in Sentinl (input, condition, transform and action) - I see strange behavior:
1) when I run the watcher manually I got the following error:
Sentinl Watchers: Transform 'script' evaluated to false: owxh5u8zup-rl1r0vmuo5i-jkr3lz991ja
but, actually, the watcher run normally, the alarm is firing and the payload is populating with the custom list payload.action_list values from the transform script (see the message text and final payload on the following screenshots):
![image](https://user-images.githubusercontent.com/32874606/32365705-fa74610e-c08b-11e7-9bbc-82c7ae2b82d7.png)

![image](https://user-images.githubusercontent.com/32874606/32366389-f3993aa0-c08e-11e7-88ae-ee6c3ab74cb6.png)

2) In the same time the scheduled executing of this watcher doesn't generate any alarms at all. 

Please advice how to resolve this issue?

**Comment by lmangani** [comment]
Hello @aquaman2 
Just to be sure, are you saying the manual vs. scheduled executions differ, or rather the transform script is not returning what you would expect - or both? Please add the "expected" results too if possible.

**Comment by aquaman2** [comment]
Yes, correct. There is no alarm generating for scheduled execution. The manual execution generating the alarm with the subject warning.

**Comment by sergibondarenko** [comment]
@aquaman2 Hi
To execute JS code in a watcher condition and transform Sentinl uses [eval()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) function. [Look here](https://github.com/sirensolutions/sentinl/blob/master/server/lib/classes/watcher.js#L269). Sometimes the `eval()` function doesn't like recent JS syntax like `Array.forEach(callback)`. At least in Node.js 6.11.X which is used by Kibana 5.5. 

For the future, test your script string by putting it into eval function like `eval("var a=0;a+=1;")`. It should return `1` if correct and `undefined` if wrong.  

In your case just rewrite the code using `for()` loop. For example, your transform:
```
payload.action_list = []; 
for (var i = 0; i < payload.aggregations.byHost.buckets.length; i++) {
  var h = payload.aggregations.byHost.buckets[i];
  for (var j = 0; j < h.byDisk.buckets.length; j++) {
    var d = h.byDisk.buckets[j];
    if (!d.byDate.buckets[1].wrLatency.value) {
      payload.action_list.push({
          host: h.key,
          disk: d.key,
          value: d.byDate.buckets[1].wrLatency.value
      }); 
    }   
  }
}
```
And the compressed form:
```
payload.action_list=[];for(var i=0;i<payload.aggregations.byHost.buckets.length;i++)for(var h=payload.aggregations.byHost.buckets[i],j=0;j<h.byDisk.buckets.length;j++){var d=h.byDisk.buckets[j];d.byDate.buckets[1].wrLatency.value||payload.action_list.push({host:h.key,disk:d.key,value:d.byDate.buckets[1].wrLatency.value})}
```

I've checked and it works for me. Please let me know if it works for you.

**Comment by aquaman2** [comment]
Hi @sergibondarenko!

Thanks, after modifying both condition and transform scripts using [for] loop - all works fine and the problem was resolved.
Let's close this issue :)

**Comment by aquaman2** [comment]
Dear @lmangani, should I open a new issue?

**Comment by lmangani** [comment]
Did you edit the issue? Last time I saw it it was resolved - reopening :)

**Comment by aquaman2** [comment]
I'm sorry, I closed this issue by mistake. The second problem (scheduled mode) still exists.

**Comment by aquaman2** [comment]
When the scheduled execution occurs I see an error in kibana log:
```
Nov  9 11:25:04 esmaas01 kibana: {"type":"log","@timestamp":"2017-11-09T08:25:04Z","tags":["status","error","Sentinl","watcher"],"pid":700,"message":"Watcher owxh5u8zup
-rl1r0vmuo5i-jkr3lz991ja: Error: Condition 'script' error for owxh5u8zup-rl1r0vmuo5i-jkr3lz991ja: TypeError: Cannot read property 'value' of undefined"}
```

I tried to modify the condition&transform scripts like following:
1) condition:
`"var match=false; for (var i = 0; i < payload.aggregations.byHost.buckets.length; i++) {var h = payload.aggregations.byHost.buckets[i]; for (var j = 0; j < h.byDisk.buckets.length; j++) {var d = h.byDisk.buckets[j];if (typeof d.byDate.buckets[1].wrLatency.value !== 'undefined' && d.byDate.buckets[1].wrLatency.value==0){match=true;}}}; match;"`

2) transform:
`"payload.action_list = []; for (var i = 0; i < payload.aggregations.byHost.buckets.length; i++) {var h = payload.aggregations.byHost.buckets[i]; for (var j = 0; j < h.byDisk.buckets.length; j++) {var d = h.byDisk.buckets[j];if (typeof d.byDate.buckets[1].wrLatency.value !== 'undefined' && d.byDate.buckets[1].wrLatency.value==0){payload.action_list.push({host:h.key,disk:d.key,value: d.byDate.buckets[1].wrLatency.value});}}}"`

by adding "typeof d.byDate.buckets[1].wrLatency.value !== 'undefined' , but this doesn't help.

**Comment by sergibondarenko** [comment]
@aquaman2 as you wrote it tells you `TypeError: Cannot read property 'value' of undefined`
> Nov  9 11:25:04 esmaas01 kibana: {"type":"log","@timestamp":"2017-11-09T08:25:04Z","tags":["status","error","Sentinl","watcher"],"pid":700,"message":"Watcher owxh5u8zup
-rl1r0vmuo5i-jkr3lz991ja: Error: Condition 'script' error for owxh5u8zup-rl1r0vmuo5i-jkr3lz991ja: TypeError: Cannot read property 'value' of undefined"}

If you have `a.value` and see an error like this, it means that `a` variable/property/object is `undefined`. Make sure that `a` exists. For example
```
if (a) {
 a.value // do something with it
}
```

**Comment by sergibondarenko** [comment]
@aquaman2 
Does [your sandbox](http://jsfiddle.net/e50L6acg/5/embedded/result/) still contain valid initial payload? If you put your condition and transform scripts there, do you have results you expect in the final payload?

**Comment by aquaman2** [comment]
Hi @sergibondarenko 
First, thanks for your help!
My current scripts below:
condition:
`"var match=false;for(var i=0;i<payload.aggregations.byHost.buckets.length;i++){var h=payload.aggregations.byHost.buckets[i];for(var j=0;j<h.byDisk.buckets.length;j++){var d=h.byDisk.buckets[j];if(d.byDate.buckets[1].wrLatency){if(d.byDate.buckets[1].wrLatency.value==0){match=true;}}}}match;"`

transform:
`"payload.action_list=[];for(var i=0;i<payload.aggregations.byHost.buckets.length;i++){var h=payload.aggregations.byHost.buckets[i];for(var j=0;j<h.byDisk.buckets.length;j++){var d=h.byDisk.buckets[j];if(d.byDate.buckets[1].wrLatency){if(d.byDate.buckets[1].wrLatency.value==0){payload.action_list.push({host:h.key,disk:d.key,value:d.byDate.buckets[1].wrLatency.value});}}}}"`

Still no luck with it.
After the latest run:
Nov 17 15:00:00 esmaas01 kibana: {"type":"log","@timestamp":"2017-11-17T12:00:00Z","tags":["status","info","Sentinl","watcher"],"pid":724,"message":"Condition 'script' evaluated to false: owxh5u8zup-rl1r0vmuo5i-jkr3lz991ja"}

Answering your questions:
1) yes, the initial payload in sandbox is still valid;
2) In sandbox with the modified condition & transform scripts I have got the expected results.

**Comment by sergibondarenko** [comment]
I think you miss a thing in your mustache template - `action_list` is a property of `payload`, define it.
```
Message:{{#payload.action_list}}Write latency:[{{value}}] on host:[{{host}}] for disk:[{{disk}}] exceeds maximum!<DLM>{{/payload.action_list}}
```
Look the following video, I tested live on Kibana 5.5.2 with your sandbox initial payload, codition and transform. Is it what you want? https://youtu.be/uf_aTIY1E-8

**Comment by aquaman2** [comment]
@sergibondarenko 
correct, the watcher works when it was executed manually. On my side I have the same behavior.
But scheduled execution doesn't generate any alarms. Can you test this scenario? Do you have the same results?

**Comment by aquaman2** [comment]
As about mustache template: in sandbox the "payload." prefix for my custom object action_list in the Body Mustache section returns empty Message.

**Comment by sergibondarenko** [comment]
@aquaman2 then sandbox is wrong. Do I receive the correct message in my video?

**Comment by aquaman2** [comment]
Yes.

**Comment by lmangani** [comment]
@aquaman2 the sandbox is not advertised as a 1:1 representation, rather a gym to familiarize with the logic elements.

**Comment by sergibondarenko** [comment]
@aquaman2 
Hi, I did a video for you to demonstrate the scheduled execution https://youtu.be/9ZdM43cCBxY

**Comment by lmangani** [comment]
Please confirm the actual ```trigger.schedule``` configuration for the affected watcher

**Comment by aquaman2** [comment]
The actual value is:
```
 "trigger": {
      "schedule": {
        "later": "every 10 mins"
      }
```
With this value the watcher also doesn't work.

**Comment by sergibondarenko** [comment]
@aquaman2 I have just tested for 5 and 10 minutes. The schedule works perfectly.
Please confirm you installed Sentinl recently in the following way:
```
./kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-5.5/sentinl-v5.5.2.zip
```

**Comment by aquaman2** [comment]
@sergibondarenko I've just reinstalled Sentinl in the way you suggested - it doesn't helps.

**Comment by lmangani** [comment]
I also cannot reproduce this issue. Was your Kibana restarted in between? Keep in mind alerts are not in ES. Are there any other active users reading this to confirm the scheduling works?

**Comment by lmangani** [comment]
@aquaman2 this seems to be a specific issue with your setup. If you'd like direct assistance and can provide remote access (or a recipe to replicate this fault elsewhere) we will be happy to help further.
In all of our tests, this scenario works and we have no other reports for the same issue so far.
If any other user has experienced this please chain to re-open this issue.

Thanks!
