### ISSUE TITLE
Unhandled rejection Error: spawn phantomjs ENOENT

### ISSUE THREAD

**Issue by himanshuarora05** [sirensolutions/sentinl#31]
Hi All,
Thanks for creating such an awesome plugin but somehow its not working on my system :(
I am working on kibana 4.6.1
OS : Linux 64 bit 
I have created a new reporter in Kibana and enable report=true in kaae.json

"email" : {
       "user":  "<myemail>",
       "password":  "<mypass>",
       "host":  "smtp.gmail.com",
       "port" :     465,
       "ssl":   true,
       "active":    true
      },
        "slack" : {
           "username":  "KAAE",
           "hook":      "https://hooks.slack.com/services/<token>",
           "channel":   "#kaae",
           "active":    false
        },
      "report" : {
         "tmp_path" : "/tmp/",
         "active":      true
      }

while sending report from kibana, I am getting following error on the server, is there a way to resolve it ?

node js version : v0.10.25

Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

**Comment by lmangani** [comment]
Hi 
Reporting is still early and has a few requirements. 
Please install phantoms and node-horseman on the system running kaae or checkout the wiki. Thanks!

**Comment by himanshuarora05** [comment]
Thanks @lmangani for the prompt reply, the issue has been resolved now. You were right about the dependencies.

**Comment by lmangani** [comment]
Thanks @himanshuarora05 for your report the dependencies will shortly be included with KaaE

**Comment by SergeyBondarenko** [comment]
I see the issue had been already resolved. Nevertheless, I still have problems with dependencies. 

Error:
```
Unhandled rejection Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
Steps to reproduce:
1. Download [Kibana 4.6.4](https://www.elastic.co/downloads/past-releases/kibana-4-6-4)
2. Unpack the tar archive and run Kibana like this `./kibana-4.6.4-linux-x86_64/bin/kibana`
3. Download [Sentinl repo](https://github.com/sirensolutions/sentinl)
4. Install Sentinl dependencies: `npm install`
5. Install Sentinl as plugin for Kibana: `gulp dev --kibanahomepath=../kibana-4.6.4-linux-x86_64`  
6. Create a new [report](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Report-Example)

To resolve:
1. Install phantomjs: `npm install phantomjs`
2. Install the related system libs: `yum install freetype fontconfig`

**Comment by lmangani** [comment]
@SergeyBondarenko indeed, but including phantomjs as a requirement seems excessive but we could go ahead and do that if that works for users (speak up!). "Other" plugins with similar functionality ship with a built in binary distribution of phantomjs for multiple systems in comparison.

**Comment by SergeyBondarenko** [comment]
The phantomjs dependency added during repositories sync: https://github.com/sirensolutions/sentinl/commit/8c3a05b57adddb9448867bec03a3627740fd7a79
